[package]
name = "sf_core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_repr = "0.1"
serde_json = "1.0"
time = { version = "0.3.41", features = ["serde"] }
sqlx = { version = "0.8", features = ["derive", "time"] }
