on:
    release:
        types: [created]

jobs:
    release:
        name: release ${{ matrix.target }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl]
        steps:
            - uses: actions/checkout@master

            - name: Install musl dependencies
              if: matrix.target == 'x86_64-unknown-linux-musl'
              run: |
                sudo apt-get update
                sudo apt-get install -y musl-tools pkg-config libssl-dev zlib1g-dev

            - name: Compile and release
              uses: rust-build/rust-build.action@v1.4.5
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                RUSTTARGET: ${{ matrix.target }}
                TOOLCHAIN_VERSION: "nightly"
                SRC_DIR: "backend"
                EXTRA_FILES: "readme.md backend/config.example.toml"

